version: "3"
services:
  frontend:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/frontend
# version: "3"
# services:
#   # --->  creamos una imagen de postgres
#   postgres:
#     image: postgres:latest
#     restart: always
#     environment:
#       - POSTGRES_USER = postgres
#       - POSTGRES_PASSWORD = 4GXBP4EvxxQX
#     volumes:
#       - postgres:/var/lib/postresql/data
#     ports:
#       - "5432:5432"
#   volumes:
#     postgres:

#   # --->  creamos una imagen de prisma
#   prisma:
#     links:
#       - postgres
#     depends_on:
#       - postgres
#     container_name: prisma
#     ports:
#       - "5555:5555"
#     build:
#       context: backend/prisma
#       dockerfile: Dockerfile
#     volumes:
#       - /app/prisma
#     backend:
#       links:
#         - postgres
#       depends_on:
#         - postgres
#       container_name: backend
#       ports:
#         - "4000:4000"
#       build:
#         context: backend
#         dockerfile: Dockerfile
#       volumes:
#         - ./backend:/app
#         - /app/node_modules
#         - /app/prisma
#     frontend:
#       container_name: frontend
#       ports:
#         - "3000:3000"
#       build:
#         context: frontend
#         dockerfile: Dockerfile
#       volumes:
#         - .:/frontend:/app
#         - /app/node_modules
#         - /app/.next
# volumes:
#   prisma:
